cassandra-01: 
  container_name: cassandra-01
  image: foxtrotsystems/apache-cassandra:2.1.12
  mem_limit: 2200000000
  environment:
    - CASSANDRA_CLUSTER_NAME=Foxtrot C*
    - CASSANDRA_DC=DC1
    - CASSANDRA_RACK=RACK1
    - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    - MAX_HEAP_SIZE=2G
    - HEAP_NEWSIZE=1G
    #- OPSCENTER_HOST=opscenter
  volumes:
    - /data/cassandra-01:/var/lib/cassandra
  ports:
    - "9042:9042"
  restart: always

cassandra-02: 
  container_name: cassandra-02
  image: foxtrotsystems/apache-cassandra:2.1.12
  mem_limit: 2200000000
  environment:
    - CASSANDRA_CLUSTER_NAME=Foxtrot C*
    - CASSANDRA_DC=DC1
    - CASSANDRA_RACK=RACK1
    - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    - MAX_HEAP_SIZE=2G
    - HEAP_NEWSIZE=1G
    - CASSANDRA_SEEDS=cassandra-01
    #- OPSCENTER_HOST=opscenter
  volumes:
    - /data/cassandra-02:/var/lib/cassandra
  restart: always

kafka:
  container_name: kafkahost
  image: foxtrotsystems/apache-kafka:0.9.0.0
  ports:
    - "2181:2181"
    - "9092:9092"
  environment:
    - ADVERTISED_HOST=kafkahost
    - ADVERTISED_PORT=9092
  restart: always

spark-master:
  container_name: sparkmaster
  hostname: sparkmaster
  mem_limit: 1500000000
  environment:
    - SPARK_MASTER_HOST=sparkmaster
  image: foxtrotsystems/apache-spark:1.6.0
  command: /usr/local/bin/start master
  ports:
    - "4040:4040"
    - "6066:6066"
    - "7077:7077"
    - "8080:8080"
  restart: always

spark-worker:
  image: foxtrotsystems/apache-spark:1.6.0
  command: /usr/local/bin/start worker
  mem_limit: 2500000000
  environment:
    - SPARK_MASTER_ENV_SPARK_MASTER_PORT=7077
  restart: always

# Monitoring 
#opscenter:
#  container_name: opscenter
#  image: foxtrotsystems/opscenter:5.2.2
#  ports:
#    - "8888:8888"
#  restart: always

cadvisor:
  container_name: cadvisor
  image: google/cadvisor:latest
  volumes: 
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
  ports:
    - "8889:8080"
