kafka:
  extends:
    file: ${PROJECT_ROOT}/spark-cassandra-docker/kafka/docker-compose.base.yml
    service: kafka
  environment:
    - SERVICE_NAME=kafka-01
    - ADVERTISED_HOST=kafka-01.service.consul
    - BROKER_ID=1

